# Generated by Django 2.1 on 2019-02-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, max_length=700)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'PEDDING'), (2, 'DONE'), (3, 'CANCEL')], default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='category/images')),
                ('keywords', models.CharField(blank=True, default='BlackSmiths - кованные изделия в Украине', max_length=255)),
                ('description', models.TextField(blank=True, default='BlackSmiths - кованные изделия в Украине', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galery/images')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MainPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_1', models.CharField(blank=True, default='Кованые ворота<br/>в Киеве и области', max_length=255)),
                ('line_2', models.CharField(blank=True, default='г. Винница, ул. Максима Шимка 12а<br/>Работаем без выходных', max_length=255)),
                ('phone', models.CharField(blank=True, default='+3 (097) 000-94-64', max_length=128)),
                ('line_3', models.CharField(blank=True, default='КОВАНЫЕ ИЗДЕЛИЯ<br/>РУЧНОЙ РАБОТЫ<br/>С ГАРАНТИЕЙ 30 ЛЕТ', max_length=255)),
                ('line_4', models.CharField(blank=True, default='Начинаем работы через 2 дня<br/>после подписания договора', max_length=255)),
                ('line_5', models.CharField(blank=True, default='Собственное производство Полностью ручная робота', max_length=255)),
                ('title', models.CharField(blank=True, default='BlackSmiths - кованные изделия в Украине', max_length=255)),
                ('keywords', models.CharField(blank=True, default='BlackSmiths - кованные изделия в Украине', max_length=255)),
                ('description', models.TextField(blank=True, default='BlackSmiths - кованные изделия в Украине', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(blank=True, max_length=128)),
                ('ln', models.CharField(blank=True, max_length=128)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('image', models.ImageField(upload_to='personal/images')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=1)),
            ],
        ),
    ]
