# Generated by Django 2.1 on 2019-02-04 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpages',
            name='ceo_image',
            field=models.ImageField(blank=True, upload_to='main/images'),
        ),
        migrations.AddField(
            model_name='mainpages',
            name='ceo_name',
            field=models.CharField(blank=True, default='Александр Трофимчук', max_length=255),
        ),
        migrations.AddField(
            model_name='mainpages',
            name='ceo_title',
            field=models.CharField(blank=True, default='Технический директор компании <br/>"BlackSmiths Place"', max_length=255),
        ),
        migrations.AlterField(
            model_name='mainpages',
            name='line_5',
            field=models.CharField(blank=True, default='Собственное производство Полностью ручная <br/> робота', max_length=255),
        ),
    ]
