# Generated by Django 2.1 on 2019-02-04 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20190204_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainpages',
            name='line_5',
            field=models.CharField(blank=True, default='Собственное производство Полностью <br/> ручная робота', max_length=255),
        ),
    ]
