# Generated by Django 2.1 on 2019-03-07 02:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20190307_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='menu_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_inside_catalog',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='product/images'),
            preserve_default=False,
        ),
    ]
