# Generated by Django 2.1 on 2019-03-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20190307_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
